APP_NAME                                : ""
NAMESPACE                               : "traduire"

GIT_COMMIT_VERSION                      : "1.0"
DELAY_IN_SECONDS                        : 5
SERVICE_PORT                            : 8081
REGION                                  : "centralus"
UTILS_CONTAINER                         : "bjd145/utils:3.16"

OTEL:
  ZIPKIN_ENDPOINT                       : "http://otel-collector.otel-system.svc.cluster.local:9411/api/v2/spans"
  ENDPOINT                              : "http://otel-collector.otel-system.svc.cluster.local:4317"
  VERSION                               : "0.98.0"

URIS:
  FRONTEND_ENDPOINT                     : ""
  KONG:                                   
    API_SECRET                          : ""
    API_ENDPOINT                        : ""

STORAGE:
  NAME                                  : ""
  CONTAINER_NAME                        : "mp3files"

ACR:
  NAME                                  : ""

APP_INSIGHTS:
  CONNECTION_STRING                     : ""
              
WORKLOAD_ID:
  NAME                                  : ""
  CLIENT_ID                             : ""
  TENANT_ID                             : ""

KEYVAULT:
  NAME                                  : ""
  SECRETS:
    SERVICE_BUS                         : "sbconnection" 
    STORAGE                             : "storagekey"
    SQL                                 : "postgresqlconnection"

SERVICE_BUS:
  TRIGGER_AUTH_NAME                     : "keda-azure-servicebus-auth"
  NAMESPACE                             : ""
  QUEUE_NAME                            : "events"
  TOPICS:
    ONCOMPLETED                         : "ontranscription_completed"
    PROCESSING                          : "ontranscription_processing"
    STARTED                             : "ontranscription_submitted" 

CERT:
  EMAIL_ADDRESS                         : "brian@bjdazure.tech"