apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ cat .Values.app_name "-api" | nospace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ cat .Values.app_name "-api" | nospace }}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: "appinsights"
        dapr.io/app-id: {{ cat .Values.app_name "-api" | nospace | quote }}
        dapr.io/log-level: "debug"
        dapr.io/http-max-request-size: "16"
      labels:
        app: {{ cat .Values.app_name "-api" | nospace }}
        aadpodidbinding: {{ .Values.msi_selector }} 
    spec:
      containers:
      - name: api
        image: {{ cat .Values.acr_name ".azurecr.io/traduire/api:" .Values.commit_version | nospace }}
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: AZURE_COGS_REGION
          value: {{ .Values.cogs_region }} 
---
apiVersion: v1
kind: Service
metadata:
  name: {{ cat .Values.app_name "-svc" | nospace }}
  labels:
    version: {{ .Values.commit_version | quote }} 
spec:
  selector:
    app: {{ cat .Values.app_name "-api" | nospace }} 
  ports:
  - port: 8081
    targetPort: 80
  type: NodePort
