apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app_name}}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app_name}}-api
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{.Values.app_name}}-api"
        dapr.io/log-level: "debug"
      labels:
        app: {{.Values.app_name}}-api
        aadpodidbinding: {{.Values.msi_selector}}
    spec:
      containers:
      - name: api
        image: {{.Values.acr_name}}.azurecr.io/traduire/api:{{.Values.commit_version}} 
        imagePullPolicy: Always
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
        envFrom:
        - secretRef:
            name: traduiresecrets
        env:
        - name: AZURE_COGS_REGION
          value: {{.Values.cogs_region}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app_name}}-svc
  labels:
    version: {{.Values.commit_version}}
spec:
  selector:
    app: {{.Values.app_name}}-api
  ports:
  - port: 8081
    targetPort: 80
  type: NodePort