apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentity
metadata:
  name: {{ cat .Values.app_name "-identity" | nospace }}
spec:
  type: 0
  resourceID: {{ .Values.msi_resource_id }}
  clientID: {{ .Values.msi_client_id }}
---
apiVersion: "aadpodidentity.k8s.io/v1"
kind: AzureIdentityBinding
metadata:
  name: {{ cat .Values.app_name "-identity-binding" | nospace }}
spec:
  azureIdentity: {{ cat .Values.app_name "-identity" | nospace }}
  selector: {{ .Values.msi_selector }}