---
apiVersion: v1
kind: Secret
metadata:
  name:  {{ cat .Values.app_name "-apikey" | nospace }}
data:
    kongCredType: a2V5LWF1dGg=
    key:  {{ .Values.kong_api_secret }}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name:   {{ cat .Values.app_name "-ingress" | nospace }}
  annotations:
    kubernetes.io/ingress.class: kong
    konghq.com/plugins: httpbin-auth
spec:
  rules:
  - http:
      paths:
      - path: /api/upload
        backend:
         serviceName:  {{ cat .Values.app_name "-svc" | nospace }}
         servicePort: 8081
---
apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: httpbin-auth
plugin: key-auth
---
apiVersion: configuration.konghq.com/v1
kind: KongConsumer
metadata:
  name:   {{ .Values.app_name }}
  annotations:
    kubernetes.io/ingress.class: kong
username:   {{ .Values.app_name }}
credentials:
-   {{ cat .Values.app_name "-apikey" | nospace }}
