apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app_name}}-oncompletion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app_name}}-oncompletion
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: "appinsights"
        dapr.io/app-id: "{{.Values.app_name}}-oncompletion"
        dapr.io/app-port: "80"
        dapr.io/log-level: "debug"
      labels:
        app: {{.Values.app_name}}-oncompletion
        aadpodidbinding: {{.Values.msi_selector}}
    spec:
      containers:
      - name: eventhandler
        image: {{.Values.acr_name}}.azurecr.io/traduire/oncompletion.handler:{{.Values.commit_version}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
        envFrom:
        - secretRef:
            name: traduiresecrets
        env:
        - name: AZURE_COGS_REGION
          value: {{.Values.cogs_region}}