apiVersion: apps/v1
kind: Deployment
metadata:
  name:  {{ cat .Values.app_name "-onstarted" | nospace }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app:  {{ cat .Values.app_name "-onstarted" | nospace }}
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/config: "appinsights"
        dapr.io/app-id: {{ cat .Values.app_name "-onstarted" | nospace | quote }}
        dapr.io/app-port: "80"
        dapr.io/log-level: "debug"
      labels:
        app:  {{ cat .Values.app_name "-onstarted" | nospace }}
        aadpodidbinding:  {{ .Values.msi_selector }}
    spec:
      containers:
      - name: eventhandler
        image: {{ cat .Values.acr_name ".azurecr.io/traduire/onstarted.handler:" .Values.commit_version | nospace }}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
        env:
        - name: AZURE_COGS_REGION
          value:  {{ .Values.cogs_region }}