apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: ontranscription-submitted
spec:
  topic: ontranscription_submitted
  route: /transcribe
  pubsubname: pubsub
scopes:
- {{ cat .Values.app_name "-onstarted" | nospace }}
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: ontranscription-pending
spec:
  topic: ontranscription_pending
  route: /status
  pubsubname: pubsub
scopes:
- {{ cat .Values.app_name "-onpending" | nospace }}
---
apiVersion: dapr.io/v1alpha1
kind: Subscription
metadata:
  name: ontranscription-completed
spec:
  topic:  ontranscription_completed
  route: /completed
  pubsubname: pubsub
scopes:
- {{ cat .Values.app_name "-oncompleted" | nospace }}