apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: {{ print .Values.APP_NAME "-config" | quote }}
  namespace: {{ .Values.NAMESPACE }}
spec:
  metric:
   enabled: true
  tracing:
    samplingRate: "1"
    stdout: true
    zipkin:
      endpointAddress: {{ print .Values.ZIPKIN_ENDPOINT | quote }}
  mtls:
    enabled: true
    workloadCertTTL: "24h"
    allowedClockSkew: "15m"