apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app_name}}-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app_name}}-api
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{.Values.app_name}}-api"
        dapr.io/log-level: "debug"
      labels:
        app: {{.Values.app_name}}-api
        aadpodidbinding: {{.Values.msi_selector}}
    spec:
      containers:
      - name: api
        image: {{.Values.acr_name}}.azurecr.io/traduire/api:{{.Values.commit_version}} 
        imagePullPolicy: Always
        env:
        - name: DAPR_BLOB_STORE_NAME
          value: {{.Values.app_name}}-storage
        - name: DAPR_PUBSUB_NAME
          value: {{.Values.app_name}}-pubsub
        - name: DAPR_STATESTORE_NAME
          value: {{.Values.app_name}}-sql
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          #readOnlyRootFilesystem: true
          #runAsUser: 1000
          #runAsGroup: 1000
---
apiVersion: v1
kind: Service
metadata:
  name: {{.Values.app_name}}-svc
  labels:
    version: {{.Values.commit_version}}
spec:
  selector:
    app: {{.Values.app_name}}
    component: api
  ports:
  - port: 8081
    targetPort: 80
  type: NodePort
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{.Values.app_name}}-ingress
spec:
  rules:
  - http: 
      paths: 
      - backend:
          serviceName: {{.Values.app_name}}-svc
          servicePort: 8081
        path: /
