apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{.Values.app_name}}-vault
spec:
  type: secretstores.azure.keyvault
  version: v1
  metadata:
  - name: vaultName
    value: {{.Values.keyvault_name}}
  - name: spnClientId
    value: {{.Values.msi_client_id}}
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{.Values.app_name}}-servicebus
spec:
  type: bindings.azure.servicebusqueues
  version: v1
  metadata:
  - name: connectionString
    secretKeyRef:
      name: {{.Values.service_bus_connection_string_secret}}
      key: {{.Values.service_bus_connection_string_secret}}
  - name: queueName
    value: {{.Values.service_bus_queue}}
auth:
  secretStore: {{.Values.app_name}}-vault
---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{.Values.app_name}}-storage
spec:
  type: bindings.azure.blobstorage
  version: v1
  metadata:
  - name: storageAccount
    value: {{.Values.storage_name}}
  - name: storageAccessKey
    secretKeyRef:
      name: {{.Values.storage_connection_string_secret}}
      key: {{.Values.storage_connection_string_secret}}
  - name: container
    value: {{.Values.storage_container}}
auth:
  secretStore: {{.Values.app_name}}-vault

---
apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: {{.Values.app_name}}-sql
spec:
  type: bindings.postgres
  version: v1
  metadata:
  - name: url 
    secretKeyRef:
      name: {{.Values.postgresql_connection_string_secret}}
      key: {{.Values.postgresql_connection_string_secret}}
auth:
  secretStore: {{.Values.app_name}}-vault