apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{.Values.app_name}}-onpending
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{.Values.app_name}}-onpending
  template:
    metadata:
      annotations:
        dapr.io/enabled: "true"
        dapr.io/app-id: "{{.Values.app_name}}-onpending"
        dapr.io/app-port: "80"
        dapr.io/log-level: "debug"
      labels:
        app: {{.Values.app_name}}-onpending
        aadpodidbinding: {{.Values.msi_selector}}
    spec:
      containers:
      - name: eventhandler
        image: {{.Values.acr_name}.azurecr.io/traduire/onpending.handler:{{.Values.commit_version}}
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "1"
            memory: 256Mi
          requests:
            cpu: "0.5"
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false