global using OpenTelemetry.Metrics;
global using OpenTelemetry.Trace;
global using OpenTelemetry.Logs;
global using OpenTelemetry.Resources;
global using System.Diagnostics.Metrics;
global using System.Diagnostics;
global using Azure.Identity;
global using Azure.Monitor.OpenTelemetry.Exporter;
global using Azure.Monitor.OpenTelemetry.AspNetCore;