name: Deploy Traduire Application Code to Azure 
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'The name of the application to deploy'
        required: true
        default: 'trad8b43xz'
      api_uri:
        description: 'The uri of the api server'
        required: true
        default: 'api.bjd.demo'

jobs:
  deploy_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Deploy API
        shell: pwsh
        run: |
          cd deploy
          .\update_firewall.ps1 -AppName ${{ github.event.inputs.app_name }} -SubscriptionName ${{ secrets.ARM_SUBSCRIPTION_ID }}
          .\deploy_application.ps1 -AppName ${{ github.event.inputs.app_name }} -Uri ${{ github.event.inputs.api_uri }} -SubscriptionName ${{ secrets.ARM_SUBSCRIPTION_ID }}
