name: Build and Push Traduire Application Code to Container Repository
on:
  workflow_dispatch:
    inputs:
      app_name:
        description: 'The name of the application to deploy'
        required: true
        default: 'trad8b43xz'
        
jobs:
  deploy_api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build Code
        if: github.event.inputs.upgrade == 'false'
        shell: pwsh
        run: |
          cd deploy
          .\build_application.ps1 -AppName ${{ github.event.inputs.app_name }} -SubscriptionName ${{ secrets.ARM_SUBSCRIPTION_ID }} -AcrName ${{ secrets.ACR_NAME }}

      - name: Package and Push Helm Chart 
        if: github.event.inputs.upgrade == 'true'
        shell: pwsh
        run: |
          cd deploy\helm
          helm package .
          helm push traduire-*.tgz oci://${{ secrets.ACR_NAME }}.azurecr.io/helm
          rm -rf traduire-*.tgz