name: Create and Deploy Traduire to Azure 
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Create and Deploy Traduire to Azure'

jobs:
  create_infrastructure:
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
          
      - name: Build
        shell: pwsh
        run: |
          cd infrastructure
          .\create_infrastructure.ps1 -AppName ${{ secrets.APP_NAME }} -Subscription ${{ secrets.ARM_SUBSCRIPTION_ID }} -Region centralus

  create_static_webapp:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
    
      - name: Create Azure StaticWebApp via Azure CLI
        uses: azure/CLI@v1
        with:
          azcliversion: 2.0.72
          inlineScript: |
            az account set -s ${{ secrets.ARM_SUBSCRIPTION_ID }}
            ##az staticwebapp create -

  deploy_api:
    needs: create_infrastructure
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Build
        shell: pwsh
        run: |
          cd deploy
          .\deploy_application.ps1 -AppName ${{ secrets.APP_NAME }} -Uri ${{ secrets.API_URI }} -Subscription ${{ secrets.ARM_SUBSCRIPTION_ID }}

  deploy_ui:
    needs: deploy_api
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          submodules: true

      - name: Build
        shell: pwsh
        run: |
         cd deploy
          .\deploy_ui.ps1 -AppName ${{ secrets.APP_NAME }} -ApiUri ${{ secrets.API_URI }} 

      - name: Deploy
        id: builddeploy
        uses: Azure/static-web-apps-deploy@v0.0.1-preview
        with:
          azure_static_web_apps_api_token: ${{ env.AZURE_STATIC_WEB_APPS_TOKEN}}
          action: 'upload'
          app_location: 'dist'
          output_location: '' 
          skip_app_build: true