name: 'Terraform'

on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Create and Deploy Traduire to Azure'

jobs:
  testing-powershell:
    name: 'test-step'
    runs-on: ubuntu-latest
    environment: production

    defaults:
      run:
        shell: powershell

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
