name: Deploy Traduire Infrastructure
on:
  workflow_dispatch:
    inputs:
      tags:
        description: 'Deploy Traduire Infrastructure to Azure'

jobs:
  deploy:
    name: Deploy Traduire
    runs-on: ubuntu-latest
    env:
        ARM_CLIENT_ID: ${{ secrets.ARM_CLIENT_ID }}
        ARM_CLIENT_SECRET: ${{ secrets.ARM_CLIENT_SECRET }}
        ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
        ARM_TENANT_ID: ${{ secrets.ARM_TENANT_ID }}
    steps:
      
    - name: "Checkout"
      uses: actions/checkout@master